### PR TITLE
Scores and classification

### LINKED ISSUE #14: Class Page: Double click on result field leads to double of results
image

If you double click the result button, the results are duplicated.

### LINKED ISSUE #15: Class Page: When student has no results → handling
If the student doesn't have any results the table should be invisible and the add result dialog should be open

### LINKED ISSUE #16: Class Page, Input Discipline - Results: When no discipline is selected
When no discipline is selected the table shouldn't be visible.

### LINKED ISSUE #17: Class Page, Table: Hide some columns in mobile view
When the table is viewed on mobile devices some columns should be removed in order the see the necessary content. An article which explains how to do this: https://stackoverflow.com/questions/38208901/bootstrap-table-hide-column-in-mobile-view

### LINKED ISSUE #19: Class Page, Add & Edit Class Dialog: Correct class name to be always capitalized
Every class name should be corrected to be capitalized, e.g. `7a` → `7A`

### LINKED ISSUE #21: Connection between class finished and result overview

### PR DESCRIPTION
**Pull request by skyliam**
Close #14  
Close #15  
Close #16  
Close #17  
Close #19  
Close #21

### CODE REVIEW

**Comment by aykborstelmann** [comment]
Yes, I see, you, unfortunately, merged the last request ...

**Comment by aykborstelmann** [comment]
And *please* use `!fixup` only with names the next time, like I showed you how IntelliJ can do this ...

**Comment by skyliam** [comment]
Oh I see im sorrry i compared in the wrong direction ... 😨😓

**Comment by skyliam** [comment]
Yes next time i will use !fixup like you showed me

**Pull request closed without merging**
