### PR TITLE
API connection

### PR DESCRIPTION
**Pull request by aykborstelmann**

### CODE REVIEW

**Comment by skyliam** [comment]
So i think we can merge this branch

**Comment by aykborstelmann** [comment]
> So i think we can merge this branch

Yes, please rebase some of this stuff before. And then select "Rebase pull request" instead of "Merge pull request". 👍

**Comment by skyliam** [comment]
Alright

**Comment by skyliam** [comment]
I totally messed things up I guess

**Comment by skyliam** [comment]
I dont make anything in this branch from now on. Can you rebase the commits? Im afraid that I destroy the whole branch if I commit the rebased branch😅

**Comment by aykborstelmann** [comment]
@skyliam Okay, I think this will be it. Please have a look at the commits and tell me if this is how you like it.

**Pull request merged**
